name: clean_architecture_template
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  # presentation only deps
  flutter_bloc: ^3.2.0
  dartz: ^0.8.9
  freezed_annotation: ^0.7.1
  get_it: ^3.1.0
  equatable: ^1.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  mockito: ^4.1.1
  lint: ^1.1.1
  build_runner:
  freezed: ^0.9.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
